package com.toy.reservationlab.common.component;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum ErrorCode {

    UNKNOWN_ERROR("COM00001"),
    LOCK_ACQUIRE_FAILED("COM00002"),

    RESTAURANT_NOT_FOUND("RST00001"),
    FUTURE_RESERVATION_EXISTS("RST00002"),

    RESERVATION_SLOT_NOT_FOUND("RSL00001"),
    CANNOT_CREATE_RESERVATION_SLOT("RSL00002"),
    PAST_SLOT_DATE("RSL00003"),
    DUPLICATE_RESERVATION_SLOT("RSL00004"),
    CANNOT_REDUCE_FULL_SLOT_CAPACITY("RSL00005"),
    CONFIRMED_RESERVATION_EXISTS("RSL00006"),

    USER_NOT_FOUND("USR00001"),
    DUPLICATE_PHONE("USR00002"),

    RESERVATION_NOT_FOUND("RSV00001"),
    CANNOT_CREATE_RESERVATION_USER("RSV00002"),
    CANNOT_CREATE_RESERVATION_TARGET_SLOT("RSV00003"),
    INVALID_PARTY_SIZE("RSV00004"),
    CAPACITY_EXCEEDED("RSV00005"),
    INVALID_RESERVATION_STATUS_TRANSITION("RSV00006");

    private final String code;
}
